services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: thegoodcookie-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/public:/app/public
    env_file: ./backend/.env
    networks:
      - thegoodcookie-network
    depends_on:
      - postgres
  postgres:
    image: postgres
    env_file: ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - thegoodcookie-network
volumes:
  assets:
  postgres-data:
networks:
  thegoodcookie-network:
    # frontend:
  #   build:
  #     context: ./frontend
  #     target: dev
  #   ports:
  #     - 3001:3000 # local:container
  #   volumes:
  #     - ./frontend/src:/app/src
  #   env_file: ./frontend/.env
