services:
  backend:
    build:
      context: ./backend
      target: dev
    container_name: thegoodcookie-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/src/
      - ./backend/public:/app/public
    env_file: ./backend/.env
    networks:
      - thegoodcookie-network
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis:latest
    env_file: ./backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - thegoodcookie-network
volumes:
  postgres-data: {}
networks:
  thegoodcookie-network: {}
