services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/src/
      - /app/public/
    env_file: ./backend/.env
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - /app/db
    ports:
      - "5433:5432"
