services:
  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/src/
      - /app/public/
    env_file: ./backend/.env
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - /app/db
    ports:
      - "5433:5432"
      # frontend:
  #   build:
  #     context: ./frontend
  #     target: dev
  #   ports:
  #     - 3001:3000 # local:container
  #   volumes:
  #     - ./frontend/src:/app/src
