import { ReactNode } from "react";
import Head from "next/head";
import AppBar from "@/components/appBar/AppBar";
import Navbar from "../appBar/navbar/Navbar";

type LayoutProps = {
  title: string;
  children: ReactNode;
};

function LayoutFull(props: LayoutProps): ReactNode {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cookicon.ico" />
      </Head>
      <AppBar />
      <main>{props.children}</main>
    </>
  );
}

export default LayoutFull;
