name: TGC Tests PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  testFrontend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests on frontend
        run: cd frontend && npm i && npm test

  testBackend:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'backend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests on backend
        run: cd backend && npm i && npm test
